name:                nation
version:             0.1.0.0
github:              "mrehayden1/nation"
license:             AllRightsReserved
author:              "Matthew Hayden"
maintainer:          "example@example.com"
copyright:           "2024 Matthew Hayden"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Nation the Game

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- AllowAmbiguousTypes
- CApiFFI
- DataKinds
- DeriveGeneric
- FlexibleContexts
- GeneralizedNewtypeDeriving
- LambdaCase
- OverloadedStrings
- PatternSynonyms
- RankNTypes
- RecordWildCards
- RecursiveDo
- ScopedTypeVariables
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators

library:
  source-dirs:           src
  c-sources:             cbits/*
  include-dirs:          includes
  dependencies:
  - aeson
  - base >= 4.7 && < 5
  - bytestring
  - containers
  - dependent-sum
  - extra
  - filepath
  - GLFW-b
  - gltf-loader
  - hgeometry
  - hgeometry-combinatorial
  - hsnoise
  - JuicyPixels
  - JuicyPixels-extra
  - lens
  - linear
  - MonadRandom
  - mtl
  - OpenGL
  - OpenGLRaw
  - ref-tf
  - reflex
  - reflex-glfw-simple
  - text
  - time
  - vector
  - StateVar

executables:
  nation:
    main:                Main.hs
    source-dirs:         src-exe/Game
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - nation

  map-test:
    main:                Main.hs
    source-dirs:         src-exe/MapTest
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

    dependencies:
    - base >= 4.7 && < 5
    - gloss
    - linear
    - nation
    - random
